config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :fridges
  post '/fridge_comments' => 'fridge_comments#create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations'}
  
  resources :users, only: [:index, :show] do
	  resources :items, only: [:index, :show, :new, :create]
	end

  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/users' => 'users#index'
  get '/expired_items' => 'items#show_expired'
  delete '/items' => 'items#destroy_collection'


end

app/models/fridge.rb
class Fridge < ApplicationRecord
	has_many :items
  has_many :fridge_comments
	has_many :users, through: :items
	validates :name, presence: true, allow_blank: false

  def fridge_form_identifier
    if name
      "#{id} - #{name}"
    else
      id
    end
  end
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
  before_action :set_fridge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  # GET /fridges
  # GET /fridges.json
  def index
    @fridges = Fridge.all
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @fridges}
    end
  end

  # GET /fridges/1
  # GET /fridges/1.json
  def show
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @fridge}
    end
  end

  # GET /fridges/new
  def new
    @fridge = Fridge.new
  end

  # GET /fridges/1/edit
  def edit
  end

  # POST /fridges
  # POST /fridges.json
  def create
    @fridge = Fridge.new(fridge_params)
    respond_to do |format|
      if @fridge.save
        format.html { redirect_to @fridge, notice: 'Fridge was successfully created.' }
        format.json { render json: @fridge, status: 201 }
      else
        format.html { render :new }
        format.json { render json: @fridge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fridges/1
  # PATCH/PUT /fridges/1.json
  def update
    respond_to do |format|
      if @fridge.update(fridge_params)
        format.html { redirect_to @fridge, notice: 'Fridge was successfully updated.' }
        format.json { render json: @fridge, status: 201 }
      else
        format.html { render :edit }
        format.json { render json: @fridge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fridges/1
  # DELETE /fridges/1.json
  def destroy
    @fridge.destroy
    respond_to do |format|
      format.html { redirect_to fridges_url, notice: 'Fridge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fridge
      @fridge = Fridge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fridge_params
      params.require(:fridge).permit(:name)
    end
end

app/helpers/fridges_helper.rb
module FridgesHelper
end

app/views/fridges/_form.html.erb
<%= form_with(model: fridge, local: true) do |form| %>
  <% if fridge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fridge.errors.count, "error") %> prohibited this fridge from being saved:</h2>

      <ul>
      <% fridge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fridges/edit.html.erb
<h1>Editing Fridge</h1>

<%= render 'form', fridge: @fridge %>

<%= link_to 'Show', @fridge %> |
<%= link_to 'Back', fridges_path %>

app/views/fridges/index.html.erb
<div class="container">
  <div class="row">
    <h1>Fridges</h1>
  </div>
  <div class="row">
    <div class="col-1">
      <a href="#" id="new_fridge_btn" class="btn btn-secondary btn-sm">New fridge</a>
    </div>
  </div>
  <div class="row">
      <div id="messages_container"></div>
  </div>
  <div class="row">
    <div class="col-4">
      <ul id="fridges_li" class="list-unstyled d-flex flex-wrap align-content-center"></ul>
    </div>
    <div class="col-8">
      <div id="display_fridge"></div>
      <div id="display_fridge_form"></div>
    </div>
  </div>
</div>

<!-- <table border=1 bordercolor=black>
  <thead>
    <tr>
      <th>Fridge ID</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="fridges_tbody">

    <% @fridges.each do |fridge| %>
      <tr>
        <td><%= fridge.id %></td>
        <td><%= fridge.name %></td>
        <td><%= link_to 'Show', fridge %></td>
        <td><%= link_to 'Edit', edit_fridge_path(fridge) %></td>
        
        <td><%= link_to 'Destroy', fridge, method: :delete, data: { confirm: 'Are you sure?' } if fridge.items == [] %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

app/views/fridges/new.html.erb
<h1>New Fridge</h1>

<%= render 'form', fridge: @fridge %>

<%= link_to 'Back', fridges_path %>

app/views/fridges/show.html.erb
<h1><%= "Fridge #{params[:id]} - #{@fridge.name}" %> </h1>

<h2>Items</h2>

<%= render partial: 'items/show', locals: {items: @fridge.items}%>

<%= link_to 'Edit', edit_fridge_path(@fridge) %> |
<%= link_to 'Back', fridges_path %>