config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :fridges
  post '/fridge_comments' => 'fridge_comments#create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations'}
  
  resources :users, only: [:index, :show] do
	  resources :items, only: [:index, :show, :new, :create]
	end

  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/users' => 'users#index'
  get '/expired_items' => 'items#show_expired'
  delete '/items' => 'items#destroy_collection'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:facebook]
  validates :name, presence: true, allow_blank: false

  has_many :user_fridges
  has_many :items
  has_many :fridge_comments
  has_many :fridges, through: :items

  def self.from_omniauth(auth)
  	
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      if auth.info.email.nil?
        user.email="#{auth.uid}@#{auth.provider}.com"
      else
        user.email = auth.info.email
      end
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name
	    user.image = auth.info.image
	  end

  end

  def user_form_identifier
    if name
      "#{email} - #{name}"
    else
      email
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      #temp
      flash[:error] = 'not successfully logged in'
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    resource.items.destroy_all
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all

    respond_to do |format|
      format.html {render :index }
      format.json {render json: @users }
    end
  end

  def show
  	@user= User.find(params[:id])
  end
end

app/views/users/index.html.erb
<div class="container">
  <div class="centered-form mx-auto">
    <h1>Users</h1>

    <table border=1 bordercolor=black>
      <thead>
        <tr>
          <th>Email</th>
          <th>Name</th>
          <th colspan="2">Items</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.name ? user.name: "Not provided" %></td>
            <td><%= user.items.length %></td>
            <td><%= link_to 'View', user_items_path(user) %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_registration_path(user) if user.provider.nil? &&current_user == user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= "User #{params[:id]}" %> </h1>

<div>Name: <%= @user.name ? @user.name : "Not Provided" %></div>
<br>
<div>Email: <%= @user.email %></div>


<h2>Items</h2>

<%= render partial: 'items/show', locals: {items: @user.items}%>

<br>
<%= link_to 'Edit', edit_user_registration_path(@user) %> |
<%= link_to 'Back', users_path %>