config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :fridges
  post '/fridge_comments' => 'fridge_comments#create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations'}
  
  resources :users, only: [:index, :show] do
	  resources :items, only: [:index, :show, :new, :create]
	end

  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/users' => 'users#index'
  get '/expired_items' => 'items#show_expired'
  delete '/items' => 'items#destroy_collection'


end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
	belongs_to :fridge
	validates_with ExpirationDateValidator, attributes: :expiration_date
	validates :name, presence: true, allow_blank: false


	def self.expired_items
		expired_item_ids = all.collect { |item| 
			expiration_date_arr = item.expiration_date.scan(/.{1,2}/).map { |s| s.to_i }
			item.id if item.expired
		}.uniq.compact
		where(id: expired_item_ids)
	end

	def self.order_by_name
		order(:name)
	end

	def expired
		expiration_date_arr = expiration_date.scan(/.{1,2}/).map { |s| s.to_i }

		(expiration_date_arr[2] < Item.today[2] ||
		expiration_date_arr[2] == Item.today[2] && expiration_date_arr[0] < Item.today[0] ||
		expiration_date_arr[2] == Item.today[2] && expiration_date_arr[0] == Item.today[0] && expiration_date_arr[1] < Item.today[1])
	end

  def fridge_attributes=(fridge_attributes)
    if fridge_attributes.values.none? {|value| value == ""}
      fridge = Fridge.find_or_create_by(fridge_attributes)
      self.fridge = fridge
    end
  end
	private

	def self.today
		@today_date ||= Date.today
		[@today_date.mon, @today_date.day, @today_date.year-2000]
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :show_expired]
  # GET /items
  # GET /items.json
  def index

    if params[:user_id]
      @items = Item.where(user_id: params[:user_id])
      @user = User.find(params[:user_id])
    else
      @items = Item.all
    end
    
    respond_to do |format|
      format.html {render :index }
      format.json {render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @item }
    end
  end

  def show_expired
  end

  # GET /items/new
  def new
    @item = Item.new
    @user = User.find(params[:user_id]) if params[:user_id]
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @fridge, status: 201  }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render json: @fridge, status: 201  }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_collection
    Item.where(id: params[:expired_item_ids]).destroy_all
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Items were successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :expiration_date, :user_id, :fridge_id, fridge_attributes: [:name])
      # params.require(:items)
    end

    # def order_params
    #   params.require(:item).permit(:name, :expiration_date, :id)
    # end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_by_resources_layout.html.erb
<table border=1 bordercolor=black>
	<thead>
		<tr>
			<% resources.each do |resource| %>
			<th>
          <%=resource.try(:email) ? "#{resource.name} - #{resource.email}":resource.name %>
      </th>
			<% end %>
		</tr>
	</thead>
    <tbody>
    	<% resources.each do |resource| %>
        <td>
        	<%= render partial: 'items/show', locals: {items: resource.items.expired_items} %>
        </td>
        <% end %>
    </tbody>
  </table>

app/views/items/_form.html.erb
  <%= form_for [@user,@item] do |f| %>

  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :item_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.text_field :expiration_date, id: :item_expiration_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label "Belongs to: " %>
    <% if @user %>
      <%= @user.user_form_identifier %>
      <% f.collection_select :user_id, User.all, :id, :user_form_identifier, {selected: user.id}, {hidden: "hidden"} %>
    <% else %>
      <%= f.collection_select :user_id, User.all, :id, :user_form_identifier, {selected: current_user.id} %>
    <%end %>
  </div>
        
  <div class="field">
    <%= f.label "Fridge: " %>
    <%= f.collection_select :fridge_id, Fridge.all, :id, :fridge_form_identifier, {selected: @item.fridge.try(:id), include_blank: "Add new"}, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.fields_for :fridge_attributes do |fridge_fields| %>
        <%= fridge_fields.label "Create new fridge to place item:" %></br>
        <%= fridge_fields.text_field :name, class: "form-control" %></br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit(nil,{class: "btn btn-primary"}) %>
  </div>

<% end %>

app/views/items/_show.html.erb
<% if items.empty?%>
  <em>no items.</em>
<% else %>
  <%= form_tag("/items", method: "delete") do %>
    <table border=1 bordercolor=black>
      <thead>
        <tr>
          <th>Name</th>
          <th>Expiration date</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% has_expired_item = false %>
        <% items.each do |item| %>
          <tr>
            <td><%= item.name %></td>
            <td><%= item.expiration_date %></td>
            <td><%= link_to 'Show', item %></td>
            <td><%= link_to 'Edit', edit_item_path(item) if current_user == item.user %></td>
            <td>
              <% if item.expired && user_signed_in? %>
              <!-- how to use hidden_field -->
              <%= check_box_tag 'expired_item_ids[]', item.id, 'checked', style: 'visibility: hidden'%>
              <% has_expired_item = true %>

              <%= 'expired!' %>
              <% end %>
            </td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? && (current_user == item.user || item.expired) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= submit_tag("Destroy all expired above", class: "btn btn-secondary btn-sm") if user_signed_in? &&has_expired_item %>
  <% end %>

<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', {item: @item, user: false}%>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <h1>Items</h1>
  </div>
  <div class="row">
    <div class="btn-group btn-group-sm">
      <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
        Create new
      </button>
      <div class="dropdown-menu">
        <% if user_signed_in? %>
          <%=link_to 'New Item for the user', new_user_item_path(current_user), {class: "dropdown-item"}%>
        <% else %>
          <%= link_to 'New Item', new_item_path, {class: "dropdown-item"} %>
        <% end %> 
        <a href="#" id="new_item_btn" class= "dropdown-item">New Item on page</a>
      </div>
        
    </div>
  </div>
  <div class="row">
    <div class="col-5">
      <ul id="items_li"></ul>
    </div>
    <div class="col-5" id="item_details_container"></div>
    <div class="col-2" id="messages_container"></div>
  </div>
</div>

<% render partial: 'show', locals: {items: @items}%>
<br>

app/views/items/new.html.erb
<div class=" mx-auto centered-form">
    <h1>New Item</h1>

    <%= render 'form', {item: @item, user: @user}%>

    <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @item.expiration_date %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/show_expired.html.erb
<h1>Expired Items</h1>
<h2>All</h2>
<%= render partial: 'items/show', locals: {items: Item.expired_items.order_by_name} %>

<h2>By Fridge</h2>
<%= render partial: 'items/by_resources_layout', locals: {resources: Fridge.all} %>


<h2>By User</h2>
<%= render partial: 'items/by_resources_layout', locals: {resources: User.all} %>