config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :fridges
  post '/fridge_comments' => 'fridge_comments#create'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations'}
  
  resources :users, only: [:index, :show] do
	  resources :items, only: [:index, :show, :new, :create]
	end

  root 'welcome#index'
  get '/about' => 'welcome#about'
  get '/users' => 'users#index'
  get '/expired_items' => 'items#show_expired'
  delete '/items' => 'items#destroy_collection'


end

app/views/layouts/_header.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="#">Fridge Share</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
  		<li class="nav-item">
				<%= link_to 'Home', root_path, {class: "nav-link"} %>
			</li>
			<li class="nav-item">
				<%= link_to 'About', about_path, {class: "nav-link"} %>
			</li>
			<li class="nav-item">
				<%= link_to 'Fridges', fridges_path , {class: "nav-link"} %>
			</li>
			<li class="nav-item">
				<%= link_to 'Users', users_path , {class: "nav-link"} %>
			</li>
			<li class="nav-item">
				<%= link_to 'Items', items_path, {class: "nav-link"} %>
			</li>
			<li class="nav-item">
				<%= link_to 'Expired items', '/expired_items', {class: "nav-link"} %>
			</li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to('Sign Up', new_user_registration_path, {class: "nav-link"}) %>
        </li>
        <li class="nav-item">
          <%= link_to('Log in', new_user_session_path, {class: "nav-link"}) %>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error", class: "alert alert-danger") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice", class: "alert alert-success") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert", class: "alert alert-warning") if flash[:alert] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FridgeShare</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>
	
  <body data-current-user-id=<%= current_user ? current_user.id : nil%>>
  	<%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>

    <%= yield %>
    <%= render 'layouts/footer' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
  
</html>